server:
  port: 8081

database:
  # host: "localhost" 
  port: 5432
  host: "host.docker.internal"
  dbname: "filter-api"
  # dbname: "mint_dashboard_api_development"
  user: "riddhij"
  password: "postgres"
  